### ISSUE TITLE
getFeaturedImage post._embedded does not exist when searching in blog

### ISSUE THREAD

**Issue by fraval13** [Noroff-FEU-Assignments/project-exam-1-LauraKaraliene#1]
When entering blog, there is a variable coming from the api which is named "_embedded". This does not exist when searching. This is why no images appears when searching, because the "post._embedded" is always null, so the function "getFeaturedImage" will always return null.

As soon as the API returns the correct data, this should work as intended.

Best reagards, Marcus's personal computer nerd

**Comment by fraval13** [comment]
If something is unclear, don't hesitate to ask.

**Comment by LauraKaraliene** [comment]
omg, thank you very much! it works :)
